import type { Metadata } from "next"
import s from "./style.module.css"
import "./global.css"

import { Sidebar, Nav } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <div className={s.wrapper}>
          <Sidebar props={[
            { name: "Профиль", link: 'hello' },
            { name: 'ligma', link: 'balls' }
          ]} />
          <main className={s.main}>
            <Nav props={[
              { name: "Профиль", link: 'hello' },
              { name: 'ligma', link: 'balls' }
            ]} />
            <section className={s.contentContainer}>
              {children}
            </section>
          </main>
        </div>
      </body>
    </html>
  );
}
